services:
  voice-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - COMPANY_NAME=${COMPANY_NAME:-Your Company}
      - WEBSITE_URL=${WEBSITE_URL:-https://your-website.com}
      - VOICE_NAME=${VOICE_NAME:-alice}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///instance/voice_assistant.db}
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
